name: iosApp
options:
  bundleIdPrefix: com.marcowong.motoman
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iosApp
      - path: ../motoman-android/assets/data
        type: folder
    info:
      path: iosApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      ENABLE_USER_SCRIPT_SANDBOXING: NO
      FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../motoman-ui/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
      OTHER_LDFLAGS: "-framework Motoman"
    preBuildScripts:
      - name: Build Framework
        script: |
          cd "$SRCROOT/.."
          ./gradlew :motoman-ui:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
